  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - product-service
      - cart-service
      - order-service
      - payment-service
      - review-service
